# frozen_string_literal: true

# Table: users
# Columns:
#  id            | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name          | text    | NOT NULL
#  email         | text    | NOT NULL
#  password_hash | text    | NOT NULL
# Indexes:
#  users_pkey      | PRIMARY KEY btree (id)
#  users_email_key | UNIQUE btree (email)

class User < Sequel::Model
end
